export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const CLEAR_ITEMS = "CLEAR_ITEMS";
export const GET_ITEM_LIST = "GET_ITEM_LIST";
export const GET_SHOPPING_CART_ITEMS = "GET_SHOPPING_CART_ITEMS";
